#ifndef CSV_ERROR_TYPE_HPP__
#define CSV_ERROR_TYPE_HPP__

#define CSV_OK							0
#define CSV_WARNING						-1
#define CSV_ERR_UNKNOWN					-2
#define CSV_ERR_IS_RUNNING				-3
#define CSV_ERR_COORDINATE				-6
#define CSV_ERR_CALC					-7
#define CSV_NOT_ENOUGH_MEM				-8
#define CSV_ERR_NULL_POINTER_PARAM		-9
#define CSV_ERR_INDEX					-10
#define CSV_ERR_ZERO_DIVISION			-11
#define CSV_ERR_BAD_PARAM				-12
#define CSV_ERR_MULTIPLY_4				-13
#define CSV_ERR_NEW_MEMORY				-14
#define CSV_ERR_FILE					-15
#define CSV_ERR_ROI_OUT_OF_RANGE		-16
#define CSV_ERR_RANGE					-17
#define CSV_ERR_CREATE_MATRIX			-18
#define CSV_ERR_MODEL_NOT_READY			-19
#define CSV_ERR_SAVE_FILE				-20
#define CSV_ERR_FILE_FORMAT				-21
#define CSV_ERR_ZERO_VECTOR				-22
#define CSV_ERR_ILLEGAL_ARRAY			-23
#define CSV_ERR_PARAM_OUT_OF_RANGE		-24
#define CSV_ERR_EULER_SYSTEM			-25
#define CSV_ERR_EXTRINSIC_PARAM			-26
#define CSV_ERR_FEW_IMAGE				-27
#define CSV_ERR_UNMATCH_IMAGE_NUM		-28
#define CSV_ERR_NOT_INSTANCE_ENGGINE	-29


#define CSV_ERR_CALC_DENOMINATOR		-51			/*The matrix expression is zero and the calculation failed*/
#define CSV_ERR_FEW_POINT				-52
#define CSV_ERR_DIFF_SIZE				-53
#define CSV_ERR_COPLANAR_POINT			-54
#define CSV_ERR_LARGE_ERROR_POINT		-55
#define CSV_ERR_NONUNIQUE				-56
#define CSV_HOMOGRAPHY_ONLY_ROTATION	-57
#define CSV_ERR_FEW_OVERLAP_POINT		-59


#define CSV_ERR_IMAGE					-101
#define CSV_ERR_TRANSFORM				-102
#define CSV_ERR_ILLEGAL_DEPTH_RANGE		-103
#define CSV_ERR_LOAD_IMAGE				-104
#define CSV_ERR_SAVE_IMAGE				-105
#define CSV_ERR_CHANNEL_NUMBER			-106
#define CSV_ERR_IMAGE_TYPE				-107
#define CSV_ERR_IMAGE_CREATE			-108
#define CSV_ERR_IMAGE_CLONE				-109
#define CSV_ERR_IMAGE_UNSUPPORT_CHN		-110
#define CSV_ERR_IMAGE_SIZE				-111
#define CSV_ERR_IMAGE_INVALID_ROI		-112
#define CSV_ERR_DEPTH_IMAGE				-113


#define CSV_ERR_IMAGE_EXTRACT_EDGE		-120
#define CSV_ERR_EDGE_TYPE				-121
#define CSV_ERR_GRADIENT_TYPE			-122


//pick and collision
#define CSV_ERR_NOT_PREPARE_FOR_ROBOT_COLL				-200
#define CSV_ERR_NOT_FIND_MATCHED_GRIPPER_ID_FOR_MODEL	-201
#define CSV_ERR_DEEP_BASEKT_PARAM						-202
#define CSV_ERR_GRIPPER_PARAM							-203
#define CSV_ERR_NO_ROBOT_HAND_INFO_FOR_MOVED_CAMERA_SYSTEM	-204


//calib error
#define CSV_ERR_CALIBRATION					-251
#define CSV_ERR_CALIB_FAILED_LOAD_FILE		-252
#define CSV_ERR_CALIB_FAILED_SAVE_FILE		-253
#define CSV_ERR_CALIB_NOT_MATCH_WITH_FILE	-254
#define CSV_ERR_CALIB_INVALID_TYPE			-255
#define CSV_PROJ_CALIB_TARGET_OVEREXPOSED	-256
#define CSV_PROJ_CALIB_TARGET_UNDEREXPOSED	-257
#define CSV_PROJ_CALIB_TARGET_LOW_CONTRAST	-258
#define CSV_ERR_CALIB_NOT_FOUND_TARGET		-259
#define CSV_ERR_CALIB_STEREO_RECTIFY		-260


#define CSV_ERR_SAC							-400
#define CSV_ERR_PARTBOX						-401
#define RES_ERR_PARTBOX_TYPE				-402
#define CSV_ERR_RESTRICT_POSE				-403
#define CSV_ERR_PRE_RECOG					-404
#define CSV_ERR_STL							-405
#define CSV_ERR_EXIST_MODEL					-406
#define CSV_ERR_FAIL_LOAD_MODEL				-407
#define CSV_ERR_BAD_MODEL					-408
#define CSV_ERR_TOO_FEW_SAC_MODEL_POINT		-409//the part box contain too few model body

//-500  <---> -600 are used by camera and projector control
#define CSV_ERR_CAMERA_NOT_FOUND		-500
#define CSV_ERR_CAMERA_NOT_CONNECTED	-501
#define CSV_ERR_ILLEGAL_INTRINSIC_PARAM -502
#define CSV_ERR_CAMERA_PARAM			-503
#define CSV_ERR_PROJECTOR_PARAM			-504
#define CSV_ERR_CAMERA_NUM				-505
#define CSV_ERR_PROJ_NUM				-506
#define CSV_ERR_CAMERA_PRJ_PARAM		-507
#define CSV_ERR_CAMERA_SAME_ID			-508
#define CSV_ERR_CAMERA_SET_INFO			-509
#define CSV_ERR_CAMERA_OPEN				-510
#define CSV_ERR_CAMERA_CLOSE			-511
#define CSV_ERR_CAMERA_SNAP				-512
#define CSV_ERR_PROJTOR_ON				-513
#define CSV_ERR_PROJTOR_OFF				-514
#define CSV_ERR_PROJTOR_RESPONSE		-515
#define CSV_ERR_PROJTOR_INNER_ERR		-516
#define CSV_ERR_CLIENT_PROJTOR			-517
#define CSV_ERR_PATTERN_SNAP			-518
#define CSV_ERR_SAME_INTRINSIC_PARAM    -519
#define CSV_UNKNOWN_CAMERA_TYPE			-520
#define CSV_ERR_CREATE_INTRINSIC_LUT	-521

#define CSV_ERR_EXPOSURE_TIME			-523
#define CSV_ERR_FAIL_TO_EXTRACT_POINTS	-524
#define CSV_ERR_FAIL_TO_EXTRACT_POINTS3D	-525


//HDRI error
#define CSV_ERR_HDRI_SNAP_NUM			-550
#define CSV_ERR_HDRI_PRE_INFO			-551
#define CSV_ERR_HDRI_IMAGING			-552
#define CSV_ERR_HDRI_TOO_BRIGHT			-553
#define CSV_ERR_HDRI_TOO_DARK			-554
#define CSV_ERR_HDRI_EXP_TIME			-555
#define CSV_ERR_HDRI_LUT				-556
#define CSV_ERR_HDRI_CREATE_IMGU8		-557
#define CSV_ERR_HDRI_CREATE_IMG_BW		-558
#define CSV_ERR_HRRI_RESULT_IMG			-559
#define CSV_ERR_HDRI_WB_CALCULATION		-560
#define CSV_ERR_INCORRECT_IMG_FOR_HDRI	-561
#define CSV_ERR_WB_IMG_CAL				-562
#define CSV_ERR_HDRI_COMBINE_IMG		-563
#define CSV_ERR_HDRI_SNAP_FUNC			-564
#define CSV_ERR_HDRI_ENABLE				-565
#define CSV_ERR_HDRI_KEY_OUT_OF_RANGE	-566
#define CSV_ERR_EXPOSURE_NOT_ASCENDING	-567
#define CSV_ERR_ILLEGAL_TOTAL_EXPOSURE	-568
#define CSV_ERR_ILLEGAL_EXPOSURE_RATE	-569
#define CSV_ERR_HDRI_NOT_PREPARED		-570
#define CSV_ERR_HDRI_NOT_FULFILL_QUALITY	-571

//create 3D points and model match
#define CSV_ERR_POINTS_MEASURE			-700
#define CSV_ERR_GET_POINTS				-701
#define CSV_ERR_3DPOINT_FROM_IMG		-702
#define CSV_ERR_POINT_LUT				-703
#define CSV_ERR_3D_POINTS_IMAGE			-704
#define CSV_ERR_SORT_RESULT				-705
#define CSV_ERR_TOO_FEW_MODEL			-706
#define CSV_ERR_RECOG_PARAM				-707
#define CSV_ERR_RECOG_FAILED			-708
#define CSV_ERR_CUR_RECOG_NO_READY		-709
#define CSV_ERR_AXIS_TRANSFORM			-710
#define CSV_ERR_TEACH_PICK_INFO			-711
#define CSV_ERR_TEACH_PICK_FILE			-712
#define CSV_ERR_BAD_POINT_IMAGE			-713
//#define CSV_ERR_CALIB_INVALID_TYPE	-714
#define CSV_ERR_FAIL_TO_LOAD_MODEL		-715
#define CSV_ERR_HDRI_IMAGE_FOR_RECG		-716
#define CSV_ERR_EMPTY_HAND_INFO_FOR_MOVED_CAMERA	-717
#define CSV_ERR_FIT_PLANE				-718
#define CSV_ERR_CREATE_PNTS_OVEREXPOSED	-719
#define CSV_ERR_CREATE_PNTS_UNDEREXPOSED	-720
#define CSV_ERR_CREATE_PNTS_LOW_CONTRAST	-721
#define CSV_ERR_DEPTH_IMAGE_TYPE			-722
#define CSV_ERR_SAVE_CREATING_PNT_LUT		-723
#define CSV_ERR_LOAD_CREATING_PNT_LUT		-724

#endif